[project]
name = "python-gui-app-template"
version = "1.0.0"
description = "Base para GUI Apps genéricos feitos com Python + PySide6"
authors = [
    {name = "D4rkw42", email = "william.conceicao042@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "pyside6 (>=6.10.1,<7.0.0)",
    "wmi (>=1.5.1,<2.0.0)",
    "requests (>=2.32.5,<3.0.0)",
]

[project.urls]
Repository = "https://github.com/D4rkw42/python-gui-app-template"
Documentation = "https://d4rkw42.github.io/python-gui-app-template/docs"

[tool.poetry]
packages = [
    { include = "client", from = "src" },
    { include = "project", from = "scripts" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "client.__main__:Main" # runs de project

[tool.poetry.plugins."console_scripts"]
compile = "project.__main__:Compile"
program = "project.__main__:ExecuteProgram"

[dependency-groups]
dev = [
    "nuitka (>=2.8.10,<3.0.0)"
]
